apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-memorystore-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Google Cloud Memorystore Terraform Module
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-memorystore.git
      sourceType: git
  ui:
    input:
      variables:
        alternative_location_id:
          name: alternative_location_id
          title: Alternative Location Id
        auth_enabled:
          name: auth_enabled
          title: Auth Enabled
        authorized_network:
          name: authorized_network
          title: Authorized Network
        connect_mode:
          name: connect_mode
          title: Connect Mode
        tier:
          name: tier
          title: Tier
          altDefaults:
            - type: ALTERNATE_TYPE_SECURITY
              value:
                Kind:
                  stringValue: BASIC
        transit_encryption_mode:
          name: transit_encryption_mode
          title: Transit Encryption Mode
    runtime:
      outputMessage: Short message to display while blueprint is deploying
      outputs:
        host:
          visibility: VISIBILITY_ROOT
